name: Bug Report
description: File a bug or issue report.
title: "[Bug]: "
labels: [ "bug" ]
assignees:
  - Kyren223
body:
  - type: markdown
    attributes:
      value: |
        *Please add an appropriate title for this issue.*

        Before reporting, search existing [issues](https://github.com/KapiMC/Kapi/issues).
        Validate that you are using an up-to-date version[^1], your issue might already be fixed!
        Questions, guidance, and usage goes in [Discord](https://discord.gg/3vcQNZA8zC).

        [^1]: This can mean latest release, pre-release, or git commit.
  - type: checkboxes
    attributes:
      label: Checklist
      description: Make sure you've checked (and actually did) all of the below.
      options:
        - label: I am using an up-to-date version.
          required: true
        - label: I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).
          required: true
  - type: input
    attributes:
      label: Kapi Version
      placeholder: 0.1.0
    validations:
      required: true
  - type: input
    attributes:
      label: Minecraft Version
      placeholder: 1.20.5
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Clear and concise description of the problem. Attach screenshots if needed, and include any errors you see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Clear and concise description of what you think should happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Minimal steps needed for the problem to occur.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs and Stack Traces
      description: Provide any logs or stack traces that may be relevant.
